package com.stangelo.saintangelo.models;

public enum UserRole {
    SUPER_ADMIN, //CAN DELETE EVERYTHING, ADD OTHER ADMINS, CEO USES THIS
    ADMIN, //CAN MANAGE DOCTORS AND QUEUING
    DOCTOR, // CAN CALL PATIENTS AND SEE DASHBOARD
    STAFF //RECEPTIONIST
}
